version: '3'
services:
  nginx:
    restart: always
    image: nginx:1.18.0 # 镜像名，根据实际情况修改
    privileged: true
    container_name: nginx-alpine
    ports:
      - '9900:80' # 映射端口
    links:
      - 'php-fpm7'
    volumes: # 挂载目录根据实际情况修改
      - D:/dd/lnmp/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - D:/dd/lnmp/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - D:/dd/DockerEnv/project/ymserp:/var/www/html/ymserp:ro
      - D:/dd/DockerEnv/project/ymserp/runtime:/var/www/html/ymserp/runtime:rw
      - D:/dd/DockerEnv/project/ymserp/public:/var/www/html/ymserp/public:rw
      - D:/dd/DockerEnv/project/erp-vue-release:/var/www/html/erp-vue-release:ro
    command: [nginx, '-g', 'daemon off;']
  php-fpm7: 
    restart: always
    image: php7.0.33-fpm:latest # 镜像名，根据实际情况修改
    privileged: true
    container_name: php-fpm
    volumes: # 挂载目录根据实际情况修改
      - D:/dd/DockerEnv/project/ymserp:/var/www/html/ymserp/:rw